[Interface]
Address = 10.13.13.3
PrivateKey = 4I0lpQXk7B84mRryjrgdLgDyDzIlQbyxCvZaPfiPEE8=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = fj691Nz6FdbiqH9q3Sc2HnEVkged+buw/Mf2Ugaj5BM=
PresharedKey = qfhvIFtyuplXvOsd5dlfBjju9uKfMiubiNKIKrkHUOc=
Endpoint = 192.168.1.222:51820
AllowedIPs = 0.0.0.0/0, ::/0
