[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = +GYNsNZygFIjTP7S1FOWFcT6swTWvnXmd8QJ8qzPxUc=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = jFbMnQTs68zM1Tqw9VRXRj37Iphtt6otTDEy5cewvg8=
PresharedKey = OQ/5Ev8YM0UoSmb/j+SZg0QCRe155m7PRqUQJFgH+zU=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = Vm5UDYUORUwYAz9axQwwsQsgELvOhy1KUX80DWLFgWY=
PresharedKey = qfhvIFtyuplXvOsd5dlfBjju9uKfMiubiNKIKrkHUOc=
AllowedIPs = 10.13.13.3/32

[Peer]
# peer3
PublicKey = 1r4UqEn8GtrnKFKTe2qeFMIckc4GWNCUEaiIYzzkJnY=
PresharedKey = WnxfrGzVehRT/1+qIcsk1IZJyZYLz45tiiuOiau6QQ8=
AllowedIPs = 10.13.13.4/32

